services:
  pos:
    image: ghcr.io/moizahmad08/samsonpos:latest
    container_name: sansons_pos
    restart: always
    environment:
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres.gxpphoctlyuwoucoummy}
      - DB_PASSWORD=${DB_PASSWORD:-sb_secret_i7r5F52MCe3AkPMFsgGy1A_2xWFyGur}
      - DB_HOST=${DB_HOST:-aws-1-ap-northeast-1.pooler.supabase.com}
      - DB_PORT=${DB_PORT:-6543}
    ports:
      - "4000:8000"
